x-env: &common-env
  environment:
    - PORT=$PORT
    - DATABASE_URL=$DATABASE_URL
    - DATABASE_HOST=$DATABASE_HOST
    - DATABASE_USER=$DATABASE_USER
    - DATABASE_PASSWORD=$DATABASE_PASSWORD
    - DATABASE_NAME=$DATABASE_NAME
    - JWT_SECRET=$JWT_SECRET
    - REDIS_PASSWORD=$REDIS_PASSWORD

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --appendonly yes --appendfsync everysec --requirepass ${REDIS_PASSWORD}

  radicx:
    build: .
    image: radicx:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    <<: *common-env
    command: pnpm start
    depends_on:
      redis:
        condition: service_healthy

  workers:
    image: radicx:latest
    restart: unless-stopped
    <<: *common-env
    command: pnpm start:workers
    depends_on:
      redis:
        condition: service_healthy
      radicx:
        condition: service_started

volumes:
  redis_data:
    driver: local