name: radicx

x-env: &common-env
  environment:
    - PORT=$PORT
    - REDIS_HOST=$REDIS_HOST
    - REDIS_PASSWORD=$REDIS_PASSWORD
    - JWT_SECRET=$JWT_SECRET
    - DATABASE_URL=$DATABASE_URL
    - DATABASE_HOST=$DATABASE_HOST
    - DATABASE_USER=$DATABASE_USER
    - DATABASE_PASSWORD=$DATABASE_PASSWORD
    - DATABASE_NAME=$DATABASE_NAME
    - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
    - GOOGLE_REDIRECT_URL=$GOOGLE_REDIRECT_URL
    - GOOGLE_CODE=$GOOGLE_CODE
    - GOOGLE_REFRESH_TOKEN=$GOOGLE_REFRESH_TOKEN

    # BOT CREDENTIALS

      #COOSALUD
    - COOSALUD_USER=$COOSALUD_USER
    - COOSALUD_PASSWORD=$COOSALUD_PASSWORD

    # SFTP
    - SFTP_HOST=$SFTP_HOST
    - SFTP_PORT=$SFTP_PORT
    - SFTP_USER=$SFTP_USER
    - SFTP_PASSWORD=$SFTP_PASSWORD

    # HORISOES
    - ODOO_USER=$ODOO_USER
    - ODOO_PASSWORD=$ODOO_PASSWORD 

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --appendonly yes --appendfsync everysec --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - "8000:8000"
    <<: *common-env
    command: pnpm start
    depends_on:
      redis:
        condition: service_healthy

  workers:
    build: .
    container_name: workers
    restart: unless-stopped
    <<: *common-env
    command: pnpm start:workers
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_started

volumes:
  redis_data:
    driver: local